### PR TITLE
Allow MPD Password to be configured in command line options

### PR DESCRIPTION
**Pull request by faithanalog**
I've been frequently annoyed when I restart my server and I have to re-enter my MPD password in YMPD, so I added an option to configure it on startup. While this does mean the password is stored on disk, for something like MPD this isn't really a big problem as long as you're not using a password you use elsewhere.

### CODE REVIEW

**Comment by d3xt3r01** [comment]
For some reason, I get a segmentation fault when using the -m param

**Comment by unknownloner** [comment]
Interesting, I'll take a look. I use the long option on my server, so I may
have done the short option incorrectly.

**Comment by unknownloner** [comment]
@d3xt3r01 I didn't understand the formatting of the optstring passed to getopt_long. Read up on it, and `-m` should be fixed now.

**Comment by d3xt3r01** [comment]
@unknownloner +1 ! Works fine now. Thanks.

**Comment by SuperBFG7** [comment]
This breaks the ympd start using the provided service file in case of an empty password

**Comment by notandy** [comment]
Thanks, should work now with empty password

**Comment by SuperBFG7** [comment]
No, or at leas not what I meant: putting `--mpdpass "$MPD_PASSWORD"` in the service file makes ympd think the next argument is the password.

**Comment by tallmtt** [comment]
Is how to configure ympd when mpd uses a password in any documentation outside of this forum?

**Pull request merged**
