### PR TITLE
add support for output enable/disable

### PR DESCRIPTION
**Pull request by kurt-vd**
I, as many others, want output control with ympd.
As C programmer, I could solve this in a few hours.
I had a hard time finding the JQuery constructions, I'm not experienced there.

The code works for me.

### CODE REVIEW

**Comment by notandy** [comment]
Nice code, the only thing that prevents me from merging is the bug appearing here: https://github.com/notandy/ympd/issues/50#issuecomment-97367868.

**Comment by kurt-vd** [comment]
> 
> Nice code, the only thing that prevents me from merging is the bug appearing here: https://github.com/notandy/ympd/issues/50#issuecomment-97367868.

I'll work on that.

**Comment by kurt-vd** [comment]
The output code is (yet again) ready to pull now.

**Comment by awikatchikaen** [comment]
Hi,

Any news on this pull request ?

**Comment by kurt-vd** [comment]
I have it working for some time now.
I didn't follow up the actual merge.

Kurt

--- Original message ---

**Pull request merged**
