### PR TITLE
Polish styles for right-hand-side buttons

### PR DESCRIPTION
**Pull request by lmanul**

### CODE REVIEW

**Comment by lmanul** [comment]
1_before
2_after

**Comment by lmanul** [comment]
Ping? :-)

**Comment by SuperBFG7** [comment]
You realize that some of the files you modified are part of the bootstrap framework?
Modifying them does not make a lot of sense and will lead to conflicts when the framework will be upgraded to a more recent version in the future.

**Comment by lmanul** [comment]
Oh, I wasn't aware you have copied over files from bootstrap. Somehow I was assuming that code from a shared library/framework would be checked out as a submodule or something like that. Anyway, indeed there's no point in modifying files from bootstrap. I'll revert this.

**Pull request closed without merging**
