### PR TITLE
Patched files to include more columns in browsing and queue mode

### PR DESCRIPTION
**Pull request by laclaro**
This change includes more columns to the broser and queue view mode in ympd.

### CODE REVIEW

**Comment by notandy** [comment]
Hey, sry for the late review.

I commented some line, also I would like to have the commits squashed. Thanks

**Comment by laclaro** [comment]
What do you mean by squashed? Could be that get_year is not used yet.

It would also be very nice to be able to view/hide columns from frontend-side.

**Comment by notandy** [comment]
https://help.github.com/articles/about-git-rebase/

**Comment by jessepeterson** [comment]
:+1: for this issue :)

**Pull request closed without merging**
